# Site
title:                    New Home Reformas
bio:                      Empresa de reformas
description:
  es: Reformas en el área metropolitana de Barcelona
  ca: Reformes a l'àrea metropolitana de Barcelona
  en: House rehabilitation in the metropolitan area of ​​Barcelona
locale:                   es_ES
baseurl:                  "" # the subpath of your site, e.g. /blog
url:                      "http://newhomereformas.com/" # the base hostname & protocol for your site
# link:                     "http://localhost:4000/"
link:                     "http://newhomereformas.com/"
background_image:         /images/bg.jpg

header1:
  es: ¿Empezamos?
  ca: Comencem?
  en: Ready?
header2:
  es: Servicios
  ca: Serveis
  en: Services
header3:
  es: Proveedores
  ca: Proveïdors
  en: Suppliers
header4:
  es: Blog
  ca: Blog
  en: Blog
header5:
  es: Contacto
  ca: Contacte
  en: Contact

view:
  es: Ver más
  ca: Veure més
  en: Read more

send:
  es: Enviar
  ca: Enviar
  en: Send

privacy:
  es: Enviando un mesaje aceptas nuestra <a id="pp">política de privacidad</a>
  ca: Enviant un missatge acceptes la nostra <a id="pp">política de privacitat</a>
  en: By sending a message you agree with our <a id="pp">privacy policy</a>

title_privacy:
  es: Política de privacidad
  ca: Política de privacitat
  en: Privacy policy

conditions:
  es: New Home Reformas utiliza y protege la información proporcionada por los usuarios con el fin de no comprometer la seguridad de sus datos. Cuando le pedimos rellenar los campos de información personal con los que usted puede ser identificado, lo hacemos asegurando que solo se empleará de acuerdo con los términos de este documento. Nuestro sitio web emplea la información con el fin de proporcionar el mejor servicio posible a los usuarios, particularmente para mantener un registro de usuarios interesados en realizar un presupuesto de obra. Es posible que sean enviados correos electrónicos periódicamente con ofertas especiales, nuevos productos y otra información que consideremos relevante para usted. Estos correos electrónicos serán enviados a la dirección que usted proporcione y podrán ser cancelados en cualquier momento respondiendo a dicho correo. Este sitio web puede contener enlaces a otros sitios que pudieran ser de su interés. Una vez que usted pulsa en estos enlaces y abandona nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o de la protección de sus datos en sitios terceros, estos sitios están sujetos a sus propias políticas de privacidad. En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web. New Home Reformas no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento en virtud de la LOPD y ley orgánica 3/2018 y podrá ejercer sus derechos ARCO.
  ca: New Home Reformes utilitza i protegeix la informació proporcionada pels usuaris per tal de no comprometre la seguretat de les seves dades. Quan li demanem omplir els camps d'informació personal amb els que vostè pot ser identificat, ho fem assegurant que només es farà servir d'acord amb les condicions d'aquest document. El nostre lloc web empra la informació per tal de proporcionar el millor servei possible als usuaris, particularment per mantenir un registre d'usuaris interessats a realitzar un pressupost d'obra. És possible que siguin enviats correus electrònics periòdicament amb ofertes especials, nous productes i altra informació que considerem rellevant per a vostè. Aquests correus electrònics seran enviats a l'adreça que vostè proporcioni i podran ser cancel·lats en qualsevol moment responent al mateix correu. Aquest lloc web pot contenir enllaços a altres llocs que puguin ser del seu interès. Una vegada que vostè accedeix a aquests enllaços i abandona la nostra pàgina, ja no tenim control sobre el lloc al qual és redirigit i per tant no som responsables dels termes o de la protecció de les seves dades en llocs de tercers, ja que aquests llocs estan subjectes a les seves pròpies polítiques de privacitat. En qualsevol moment vostè pot restringir la recopilació o l'ús de la informació personal que és proporcionada al nostre lloc web. New Home Reformes no vendrà, cedirà o distribuirà la informació personal que és recopilada sense el seu consentiment en virtut de la LOPD i llei orgànica 3/2018 i podrà exercir els seus drets ARCO.
  en: New Home Reformas uses and protects the information that is provided by users in order not to compromise the security of their data. When we ask you to fill in the fields of personal information with which you can be identified, we do so by ensuring that it will only be used in accordance with the terms and conditions of this document. Our website uses the information in order to provide the best possible service to users, particularly to maintain a registry of users interested in a refurbishing budget. E-mails may be sent periodically through our site with special offers, new products and other information that we consider relevant to you. These emails will be sent to the address you provide and may be canceled at any time by replying to such email. This website may contain links to other sites that may be of interest to you. Once you click on these links and leave our page, we no longer have control over the site to which you are redirected and therefore we are not responsible for the terms or the protection of your data in third party sites, these sites are subject to their own privacy policies. At any time you may restrict the collection or use of personal information that is provided to our website. New Home Reformas will not sell, assign or distribute the personal information that is collected without your consent under the LOPD and organic law 3/2018 and may exercise their rights ARCO.

contact_name:
  es: Nombre
  ca: Nom
  en: Name

contact_email:
  es: Correo
  ca: Correu
  en: Email

contact_phone:
  es: Teléfono
  ca: Telèfon
  en: Phone

contact_message:
  es: Mensaje
  ca: Missatge
  en: Message

contact_location:
  es: Ubicación
  ca: Ubicació
  en: Location

contact_nif: NIF
nif: "B66554445"

# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
# formspree_thankyou_page:  /thank-you

# Polyglot
permalink: pretty

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
# permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   default

# Social
# analytics-id:       "default"
# twitter:            default
# facebook:           default
# instagram:          default

# Personal
location:
  es: Provincia de Barcelona
  ca: Província de Barcelona
  en: Province of Barcelona

phone:              666633272
email:              newhomereformasbcn@gmail.com

# Gems/Plugins
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
#  - jekyll-paginate

# paginate: 6
# paginate_path: "/blog/page:num/"

# jekyll-mentions:
#     base_url: https://github.com

# Exclude list
exclude: [Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, Rakefile, old]


# HTTP Headers
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
